#!/usr/bin/bash

# Install stuff via dotbot
set -e
if [ `uname` == "Darwin" ]; then
    CONFIG="osx.conf.yaml"
else
    CONFIG="linux.conf.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# TODO: Check for existence of brew/brew cask and make the user install them first
installBrewStuff() {
    '(karabiner seil)
}
