#!/usr/bin/bash

# Install stuff via dotbot
set -e
if [ `uname` == "Darwin" ]; then
    CONFIG="osx.conf.yaml"
else
    CONFIG="linux.conf.yaml"
    # Latest git
    # https://www.howtoforge.com/install-git-on-ubuntu-13.1
    sudo apt-get install git
    sudo apt-get update
    sudo add-apt-repository ppa:git-core/ppa

    # zsh
    sudo apt-get install zsh
    chsh -s /bin/zsh

    # antigen
    curl -L https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh > antigen.zsh
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# TODO: Check for existence of brew/brew cask and make the user install them first
installBrewStuff() {
    '(karabiner seil)
}
