;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-delete-backward-char-and-join
        evil-indent-i-indent
        evil-jumper/backward
        keyboard-quit
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-next-visual-line
        evil-previous-visual-line
        evil-search-next
        ))
